CREATE OR REPLACE DATABASE task_db;
CREATE OR REPLACE SCHEMA task_sch;

USE DATABASE task_db;
USE SCHEMA task_sch;

CREATE TASK MANAGED_SCHEDULED_TASK 
-- execute 0 minutes of every hour
SCHEDULE="USING CRON 0 * * * * UTC"
-- optional parameter to manage the warehouse size
TARGET_COMPLETION_INTERVAL='10 MINUTE'
SERVERLESS_TASK_MIN_STATEMENT_SIZE='SMALL'
SERVERLESS_TASK_MAX_STATEMENT_SIZE='LARGE'
AS
SELECT 1;

SHOW TASKS LIKE 'MANAGED_SCHEDULED_TASK%';

ALTER TASK MANAGED_SCHEDULED_TASK RESUME;


ALTER TASK MANAGED_SCHEDULED_TASK SUSPEND;

--tear down
DROP TASK MANAGED_SCHEDULED_TASK;
DROP database task_db;
